defaults:
  - base_region_zarr_config
  - model/GETRegionPretrain@_here_
  - finetune/v1_pretrain@finetune
  - machine/pc
  - _self_

assembly: "hg38"

dataset:
    zarr_path: /home/xf2217/Projects/get_model/tutorials/output.zarr
    celltypes: astrocyte
    num_region_per_sample: 200
    transform: null
    leave_out_celltypes: null
    leave_out_chromosomes: 'chr11'
    quantitative_atac: false
    sampling_step: 100
    mask_ratio: 0.0

training:
  save_ckpt_freq: 1
  epochs: 100
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false

optimizer:
  lr: 0.0001
  min_lr: 0.0001
  weight_decay: 0.05
  opt: "adamw"
  opt_eps: 1e-8
  opt_betas: [0.9, 0.999]

run:
  project_name: "finetune_tutorial"
  run_name: "debug"

task:
  layer_names: ['region_embed']
  test_mode: "interpret"
  gene_list: 'MYC,SOX10,SOX2,RET'


finetune:
  pretrain_checkpoint: false
  strict: true
  use_lora: false
  checkpoint: "/home/xf2217/Projects/get_checkpoints/Astrocytes/checkpoint-best.pth"
  patterns_to_freeze: []

eval_tss: true
log_image: true

hydra:
  job:
    name: ${run.project_name}_${run.run_name}
  run:
    dir: ${machine.output_dir}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
